### ISSUE TITLE
Error executing action `stop` on resource 'service[kafka]'

### ISSUE THREAD

**Issue by uohzxela** [cerner/cerner_kafka#10]
Encountered this error after executing 'untar kafka binary' action:

<pre>
  * execute[untar kafka binary] action run
    - execute tar zxf /var/chef/cache/kafka_2.9.2-0.8.1.1.tgz
  * service[kafka] action stop
    
    ================================================================================
    Error executing action `stop` on resource 'service[kafka]'
    ================================================================================
    
    Errno::ENOENT
    -------------
    No such file or directory - /etc/init.d/kafka stop
    
    Resource Declaration:
    ---------------------
    # In /home/ubuntu/chef-solo/cookbooks-2/cerner_kafka/recipes/default.rb
    
    200: service "kafka" do
    201:   action [:enable, :start]
    202: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/ubuntu/chef-solo/cookbooks-2/cerner_kafka/recipes/default.rb:200:in `from_file'
    
    service("kafka") do
      action [:enable, :start]
      supports {:restart=>false, :reload=>false, :status=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      service_name "kafka"
      pattern "kafka"
      cookbook_name :cerner_kafka
      recipe_name "default"
    end
</pre>

Solution: 

Create kafka service file before executing service commands. Move the template creation for /etc/init.d/kafka to the top like this in my forked repo: https://github.com/uohzxela/cerner_kafka/blob/master/recipes/default.rb#L114

**Comment by bbaugher** [comment]
Fixed by #13
