### ISSUE TITLE
Create chroot for kafka in zookeeper

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_kafka#11]

**Comment by bbaugher** [comment]
#12 would make this easier

**Comment by bbaugher** [comment]
This is actually not terribly easy. There are basically 2 zookeeper clients in ruby https://github.com/zk-ruby/zookeeper and https://github.com/lwoggardner/zkruby. The first uses native extensions to hook into a version of zookeeper in C which doesn't install successfully with Chef's gems. The second gem is a pure ruby gem but doesn't seem well supported and I had problems getting it to work.

**Comment by emmanuelidi** [comment]
May not be necessary anymore: https://issues.apache.org/jira/browse/KAFKA-404

**Comment by bbaugher** [comment]
Ugh I looked but apparently not hard enough. Thanks for the info!

**Comment by bbaugher** [comment]
No longer doing this
