### ISSUE TITLE
Remove broker config defaults

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_kafka#14]
We add in a number of broker defaults that were originally our settings. These may not make sense for others and may not even be used by us anymore.

**Comment by mkwhitacre** [comment]
Does Kafka have a nice documentation link we could use so consumers would know what the defaults are now that we are removing some?

**Comment by bbaugher** [comment]
Yes we should be able to send them here, http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by bbaugher** [comment]
Done by #15
