### ISSUE TITLE
Support setting topic configuration

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_kafka#20]
We have a need to set topic level configuration like retention policies. We would also like to be able to remove this configuration if necessary. It would also be helpful to be able to specify config for multiple topics either via common config or possibly wildcards.

**Comment by TD-4242** [comment]
It might be nice to have a topic creation LWRP that could take configuration policy like retention, replication, partitions etc...

**Comment by bbaugher** [comment]
We've come up with a different way to do this so we are canceling this
