### ISSUE TITLE
kafka stdout logs same thing as server.log

### ISSUE THREAD

**Issue by bbaugher** [cerner/cerner_kafka#29]
The kafka stdout which we send to a log file contains the same log as the primary log file server.log. Additionally we don't seem to have any log rolling on this file which can grow to be rather large.

We should consider either adding log rolling or removing the logging of stdout.

**Comment by TD-4242** [comment]
I still think pushing stdout to a log is important for stuff not caught by the normal logging system.  We should be able to turn off other logging from log4j/logback to not go to stdout though.

**Comment by bbaugher** [comment]
Yes it would probably be good to remove [logging to stdout](https://github.com/cerner/cerner_kafka/blob/master/attributes/default.rb#L44-L47) and look at adding log rolling for those files

**Comment by bbaugher** [comment]
Done by #30
